{% set version = "0.4" %}
{% set sha256 = "47b5cb48f8e036497cd73b96de305cecb4070e9ecbc908724afcbd2224edccde" %}

package:
  name: port-for
  version: {{ version }}

source:
  fn: port_for-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/port-for/port-for-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - port_for
  commands:
    - port-for --version

about:
  home: https://github.com/kmike/port-for/
  license: MIT
  summary: 'port-for is a command-line utility and a python library that helps with local TCP ports managment'
  description: |
    port-for is a command-line utility and a python library that helps with local TCP ports managment.
    port-for <foo> script finds an unused port and associates it with <foo>. Subsequent calls will
    return the same port number.
  dev_url: https://github.com/kmike/port-for

extra:
  recipe-maintainers:
    - chohner
