{% set version = "0.7.0" %}
{% set sha256 = "c8e948fd833b45af3814603fb11107ca2e58022ad6e6e24ae7428f8cd75cdd29" %}
{% set pkg_name = "port-for" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: port_for-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
  run:
    - python >=3.7

test:
  imports:
    - port_for
  commands:
    - port-for --version

about:
  home: https://github.com/kmike/port-for/
  license: MIT
  license_file: LICENSE.txt
  summary: port-for is a command-line utility and a python library that helps with local TCP ports managment
  description: |
    port-for is a command-line utility and a python library that helps with local TCP ports managment.
    port-for <foo> script finds an unused port and associates it with <foo>. Subsequent calls will
    return the same port number.
  dev_url: https://github.com/kmike/port-for

extra:
  recipe-maintainers:
    - chohner
