{% set name = "port-for" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/port_for-{{ version }}.tar.gz
  sha256: 2d597e5854a1b323b17eba8ae0630784c779857abde5e22444c88d233a60f953

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - port_for
  commands:
    - port-for --version

about:
  home: https://github.com/kmike/port-for/
  license: MIT
  license_file: LICENSE.txt
  summary: port-for is a command-line utility and a python library that helps with local TCP ports managment
  description: |
    port-for is a command-line utility and a python library that helps with local TCP ports managment.
    port-for <foo> script finds an unused port and associates it with <foo>. Subsequent calls will
    return the same port number.
  dev_url: https://github.com/kmike/port-for

extra:
  recipe-maintainers:
    - chohner
    - mariusvniekerk
