{% set name = "port-for" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/port_for-{{ version }}.tar.gz
  sha256: fc7713e7b22f89442f335ce12536653656e8f35146739eccaeff43d28436028d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - port_for
  commands:
    - port-for --version

about:
  home: https://github.com/kmike/port-for/
  license: MIT
  license_file: LICENSE.txt
  summary: port-for is a command-line utility and a python library that helps with local TCP ports managment
  description: |
    port-for is a command-line utility and a python library that helps with local TCP ports managment.
    port-for <foo> script finds an unused port and associates it with <foo>. Subsequent calls will
    return the same port number.
  dev_url: https://github.com/kmike/port-for

extra:
  recipe-maintainers:
    - chohner
    - mariusvniekerk
